name = "glemo"
version = "1.0.1"
description = "Simple function memoization over Erlang ETS / JavaScript Map for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "glemo" }

[dependencies]
carpenter = ">= 0.3.1"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
cleam = ">= 1.5.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
